DELETE http://localhost:8085/collection/remove/1

###

GET http://localhost:8085/collection/industries

###

POST http://localhost:8085/collection/client
Content-Type: application/json

REtail


###

PUT http://localhost:8085/change/2
Content-Type: application/json

Automation