GET http://localhost:8085/patient/

###

POST http://localhost:8085/patient/
Content-Type: application/json

{
    "patientName": "Brindha",
    "age": 19,
    "bloodGroup": "B+",
    "address": "Namakkal",
    "contact":9876556782,
    "issue": "Psychological disorder",
    "doctorId":5
}

###

DELETE http://localhost:8085/patient/2

###

PUT http://localhost:8085/patient/
Content-Type: application/json

{
    "patientId":3,
    "patientName": "Gokul",
    "age": 19,
    "bloodGroup": "A+",
    "address": "Rasipuram",
    "contact":987656767,
    "issue": "Skin",
    "doctorId":5
}

###

GET http://localhost:8085/patient/5