GET http://localhost:8085/patient/

###

POST http://localhost:8085/patient/
Content-Type: application/json

{
    "patientName": "Baasha",
    "age": 20,
    "bloodGroup": "O+",
    "address": "Salem",
    "contact":87654567894,
    "issue": "Fever"
}

###

DELETE http://localhost:8085/patient/2

###

PUT http://localhost:8085/patient/
Content-Type: application/json

{
    "patientId": 10,
    "patientName": "Baasha",
    "age": 20,
    "bloodGroup": "O+",
    "address": "SAlem",
    "contact": 9876565523,
    "issue": "Cold"
}